-- Insert questions (id will auto-increment)

INSERT INTO questions (question_text, correct_answer) VALUES ('Which is the largest continent in the world?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the capital of Australia?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which planet is known as the Red Planet?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the largest ocean in the world?', 'D');
INSERT INTO questions (question_text, correct_answer) VALUES ('Who wrote the play "Romeo and Juliet"?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the chemical symbol for Gold?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which country is home to the Eiffel Tower?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the tallest mountain in the world?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the currency of Japan?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which gas do plants absorb from the atmosphere during photosynthesis?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('Where is India Gate located?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which continent is the only one with land in all four hemispheres?', 'D');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the national aquatic animal of India?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('Who painted the Mona Lisa?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the powerhouse of the cell?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which element has the chemical symbol ''O''?', 'C');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which is the largest coral reef system in the world?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which country has three capitals?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('Which city is known for its diamond industry?', 'B');
INSERT INTO questions (question_text, correct_answer) VALUES ('What is the largest cell in the human body?', 'B');

-- Insert options (id will auto-increment, question_id references questions table)

INSERT INTO options (question_id, option_label, option_text) VALUES (1, 'A', 'Africa');
INSERT INTO options (question_id, option_label, option_text) VALUES (1, 'B', 'Asia');
INSERT INTO options (question_id, option_label, option_text) VALUES (1, 'C', 'Europe');
INSERT INTO options (question_id, option_label, option_text) VALUES (1, 'D', 'North America');
INSERT INTO options (question_id, option_label, option_text) VALUES (2, 'A', 'Sydney');
INSERT INTO options (question_id, option_label, option_text) VALUES (2, 'B', 'Canberra');
INSERT INTO options (question_id, option_label, option_text) VALUES (2, 'C', 'Melbourne');
INSERT INTO options (question_id, option_label, option_text) VALUES (2, 'D', 'Perth');
INSERT INTO options (question_id, option_label, option_text) VALUES (3, 'A', 'Venus');
INSERT INTO options (question_id, option_label, option_text) VALUES (3, 'B', 'Mars');
INSERT INTO options (question_id, option_label, option_text) VALUES (3, 'C', 'Jupiter');
INSERT INTO options (question_id, option_label, option_text) VALUES (3, 'D', 'Saturn');
INSERT INTO options (question_id, option_label, option_text) VALUES (4, 'A', 'Atlantic Ocean');
INSERT INTO options (question_id, option_label, option_text) VALUES (4, 'B', 'Indian Ocean');
INSERT INTO options (question_id, option_label, option_text) VALUES (4, 'C', 'Arctic Ocean');
INSERT INTO options (question_id, option_label, option_text) VALUES (4, 'D', 'Pacific Ocean');
INSERT INTO options (question_id, option_label, option_text) VALUES (5, 'A', 'Charles Dickens');
INSERT INTO options (question_id, option_label, option_text) VALUES (5, 'B', 'William Shakespeare');
INSERT INTO options (question_id, option_label, option_text) VALUES (5, 'C', 'Mark Twain');
INSERT INTO options (question_id, option_label, option_text) VALUES (5, 'D', 'Jane Austen');
INSERT INTO options (question_id, option_label, option_text) VALUES (6, 'A', 'Go');
INSERT INTO options (question_id, option_label, option_text) VALUES (6, 'B', 'Gd');
INSERT INTO options (question_id, option_label, option_text) VALUES (6, 'C', 'Au');
INSERT INTO options (question_id, option_label, option_text) VALUES (6, 'D', 'Ag');
INSERT INTO options (question_id, option_label, option_text) VALUES (7, 'A', 'Italy');
INSERT INTO options (question_id, option_label, option_text) VALUES (7, 'B', 'Spain');
INSERT INTO options (question_id, option_label, option_text) VALUES (7, 'C', 'France');
INSERT INTO options (question_id, option_label, option_text) VALUES (7, 'D', 'Germany');
INSERT INTO options (question_id, option_label, option_text) VALUES (8, 'A', 'K2');
INSERT INTO options (question_id, option_label, option_text) VALUES (8, 'B', 'Kangchenjunga');
INSERT INTO options (question_id, option_label, option_text) VALUES (8, 'C', 'Mount Everest');
INSERT INTO options (question_id, option_label, option_text) VALUES (8, 'D', 'Makalu');
INSERT INTO options (question_id, option_label, option_text) VALUES (9, 'A', 'Yuan');
INSERT INTO options (question_id, option_label, option_text) VALUES (9, 'B', 'Won');
INSERT INTO options (question_id, option_label, option_text) VALUES (9, 'C', 'Yen');
INSERT INTO options (question_id, option_label, option_text) VALUES (9, 'D', 'Ringgit');
INSERT INTO options (question_id, option_label, option_text) VALUES (10, 'A', 'Oxygen');
INSERT INTO options (question_id, option_label, option_text) VALUES (10, 'B', 'Nitrogen');
INSERT INTO options (question_id, option_label, option_text) VALUES (10, 'C', 'Carbon Dioxide');
INSERT INTO options (question_id, option_label, option_text) VALUES (10, 'D', 'Hydrogen');
INSERT INTO options (question_id, option_label, option_text) VALUES (11, 'A', 'Mumbai');
INSERT INTO options (question_id, option_label, option_text) VALUES (11, 'B', 'Delhi');
INSERT INTO options (question_id, option_label, option_text) VALUES (11, 'C', 'Kolkata');
INSERT INTO options (question_id, option_label, option_text) VALUES (11, 'D', 'Chennai');
INSERT INTO options (question_id, option_label, option_text) VALUES (12, 'A', 'Asia');
INSERT INTO options (question_id, option_label, option_text) VALUES (12, 'B', 'Australia');
INSERT INTO options (question_id, option_label, option_text) VALUES (12, 'C', 'South America');
INSERT INTO options (question_id, option_label, option_text) VALUES (12, 'D', 'Africa');
INSERT INTO options (question_id, option_label, option_text) VALUES (13, 'A', 'Crocodile');
INSERT INTO options (question_id, option_label, option_text) VALUES (13, 'B', 'River Dolphin');
INSERT INTO options (question_id, option_label, option_text) VALUES (13, 'C', 'Whale');
INSERT INTO options (question_id, option_label, option_text) VALUES (13, 'D', 'Turtle');
INSERT INTO options (question_id, option_label, option_text) VALUES (14, 'A', 'Vincent van Gogh');
INSERT INTO options (question_id, option_label, option_text) VALUES (14, 'B', 'Leonardo da Vinci');
INSERT INTO options (question_id, option_label, option_text) VALUES (14, 'C', 'Pablo Picasso');
INSERT INTO options (question_id, option_label, option_text) VALUES (14, 'D', 'Michelangelo');
INSERT INTO options (question_id, option_label, option_text) VALUES (15, 'A', 'Nucleus');
INSERT INTO options (question_id, option_label, option_text) VALUES (15, 'B', 'Ribosome');
INSERT INTO options (question_id, option_label, option_text) VALUES (15, 'C', 'Mitochondria');
INSERT INTO options (question_id, option_label, option_text) VALUES (15, 'D', 'Chloroplast');
INSERT INTO options (question_id, option_label, option_text) VALUES (16, 'A', 'Gold');
INSERT INTO options (question_id, option_label, option_text) VALUES (16, 'B', 'Osmium');
INSERT INTO options (question_id, option_label, option_text) VALUES (16, 'C', 'Oxygen');
INSERT INTO options (question_id, option_label, option_text) VALUES (16, 'D', 'Ozone');
INSERT INTO options (question_id, option_label, option_text) VALUES (17, 'A', 'Red Sea Coral Reef');
INSERT INTO options (question_id, option_label, option_text) VALUES (17, 'B', 'Great Barrier Reef');
INSERT INTO options (question_id, option_label, option_text) VALUES (17, 'C', 'New Caledonia Barrier Reef');
INSERT INTO options (question_id, option_label, option_text) VALUES (17, 'D', 'Mesoamerican Reef');
INSERT INTO options (question_id, option_label, option_text) VALUES (18, 'A', 'India');
INSERT INTO options (question_id, option_label, option_text) VALUES (18, 'B', 'South Africa');
INSERT INTO options (question_id, option_label, option_text) VALUES (18, 'C', 'Netherlands');
INSERT INTO options (question_id, option_label, option_text) VALUES (18, 'D', 'Switzerland');
INSERT INTO options (question_id, option_label, option_text) VALUES (19, 'A', 'Mumbai');
INSERT INTO options (question_id, option_label, option_text) VALUES (19, 'B', 'Surat');
INSERT INTO options (question_id, option_label, option_text) VALUES (19, 'C', 'Jaipur');
INSERT INTO options (question_id, option_label, option_text) VALUES (19, 'D', 'Ahmedabad');
INSERT INTO options (question_id, option_label, option_text) VALUES (20, 'A', 'Nerve Cell');
INSERT INTO options (question_id, option_label, option_text) VALUES (20, 'B', 'Ovum (Egg Cell)');
INSERT INTO options (question_id, option_label, option_text) VALUES (20, 'C', 'Muscle Cell');
INSERT INTO options (question_id, option_label, option_text) VALUES (20, 'D', 'White Blood Cell');